### ISSUE TITLE
Set text alignment on "Display Text" block

### ISSUE THREAD

**Issue by deradam** [alankrantas/pxt-MAX7219_8x8#5]
Hi Alan,

thanks for the awesome lib. It seems like the community takes care of everything for the micro:bit 👍 

I want to display the distance on a 4x 8x8 matrix. Rotation works perfectly fine. Now when I display the distance, it renders "left-aligned". So the text is jumping from like "120 cm" to "3 cm" for example. So the "cm" is moving left to right and back.

Do you see any chance to implement this feature? Or maybe you can give me a hint where to look at in the source code?

Cheers!

**Comment by alankrantas** [comment]
The offset option in the "Display text" block allows you to print texts started at any place on the display.

A 4x 8x8 matrix has 4x8=32 columns, so offset can be set as 0 to 31 (0 = start for the first column from the left). Store your text in a variable, get its length, and set the offset as (31 - length).

![microbit-screenshot](https://user-images.githubusercontent.com/44191076/96062241-c6b58e00-0ec7-11eb-90e3-12d0ff5e4ca5.png)

You can also utilize this to do some animation effects, like scrolling texts from right to left, back and forth or blinking and stuff.

Add a new block is simple enough - but there would be adding more lines of code than above (I would have to define a new block as well). Since this driver already used up a lot of memory space of micro:bit, I am hesitate to do that now. (Maybe not until the new version of micro:bits become widely used.)

**Comment by deradam** [comment]
Hi Alan, thanks for the promt answer, very much appreciated.

I checked your proposal and I am not sure if I am getting it right or wrong but it doesn't work for me.

So the when I calculate 31 - length of text - let's say "10 cm", then length ("10 cm") is 5. 31 -5 is 26. Offset 26 however is not enought to show the string I want to show.

I guess I would need to have access to the width of the text instead of the length. I have seen that you have such a matrix inside your source code. Is there any way to get access from outside to this width array?

Cheers and greetings from Germany :)

**Comment by alankrantas** [comment]
Yeah, I totally forgot that the characters have their own widths. My bad.

I made a update with a new block. Test OK on my own device. Re-import the driver and it should be there.

![microbit-screenshot](https://user-images.githubusercontent.com/44191076/96159460-3fa7fa80-0f47-11eb-878e-db96557b8480.png)

**Comment by deradam** [comment]
Hi @alankrantas,
I was only able to test your fixes now. And what should I say, works like a charm! Thanks a lot for the awesome and speedy support!
Cheers! 🥇
