### ISSUE TITLE
Add function to replace character in font library

### ISSUE THREAD

**Issue by objorke** [alankrantas/pxt-MAX7219_8x8#6]
For example, replace "1" with a character that has the same width as the other digits!

**Comment by alankrantas** [comment]
You can "print" a custom character using one of the blocks. It will just be a mess to simply let you modify hidden global variables.

**Comment by objorke** [comment]
This works well in the MD_Parola Arduino library. We simply replace the "." and "1" characters and get exactly what we need.
https://github.com/MajicDesigns/MD_Parola/blob/main/src/MD_Parola.h#L989

**Comment by alankrantas** [comment]
I understand what you are trying to do. But this is _not_ Arduino. I had to cut down some original functions so that this extension can run on micro:bit v1's smaller RAM, especially people (including STEM educators) would often run it with several other sensor extensions.

And like what I've said in your duplicated issue: the font is not monospaced (equal width fonts) in the first place. Changing only one character is an ugly, unnecessary inconsistency for all other users.
